### ISSUE TITLE
Community org page publishing: Can publish despite a section still having errors

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#809] opened 2022-08-15 17:03 UTC
I was able to publish the page despite step 2/4 (groups the organization can connect to) still producing errors due to missing fields. When it publishes and I go to the view page, that section just shows up as empty.

**Comment by greatislander** [comment] 2022-08-15 17:15
Duplicate of #595.

**Closed as not planned by greatislander** 2022-08-15 17:15 UTC
Labels: bug
