### ISSUE TITLE
FRO page creation: not entering the required French translations did not lead to errors and page was saved

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-in-action/platform#837] opened 2022-08-16 18:51 UTC
Although the French translations were required, we could still save the page without entering French translations, except for the project name. Later, we were able to delete the English translation and notice the published page only showed the French project name and the rest of the fields were empty.

**Comment by greatislander** [comment] 2022-08-24 12:42
Duplicate of #728. Ensure that 'required' text does not appear for alternate languages.

**Closed as not planned by greatislander** 2022-08-24 12:42 UTC
Labels: bug, duplicate, accessibility and usability
