### ISSUE TITLE
Project creation: invalid project dates crashes the application

### ISSUE THREAD

**Issue by chosww** [accessibility-in-action/platform#887] opened 2022-08-19 13:32 UTC
When non valid year or day value is entered in the project date, the application shows error 500.

Error message:

Cannot assign string to property App\Http\Livewire\DatePicker::$year of type ?int
Cannot assign string to property App\Http\Livewire\DatePicker::$day of type ?int

**Comment by greatislander** [comment] 2022-08-19 17:29
This is a duplicate of #832.

**Closed as not planned by greatislander** 2022-08-19 17:29 UTC
Labels: bug, duplicate
