### ISSUE TITLE
English language can't be removed from page translations

### ISSUE THREAD

**Issue by sepidehshahi** [accessibility-in-action/platform#834] opened 2022-08-16 18:04 UTC
When creating an organization page or a project, on the page/project translation page there are four languages by default. 

- [ ] Selecting the remove button for English would remove other languages.
- [ ] If English is the default language we shouldn't show the remove button

**Comment by greatislander** [comment] 2022-08-16 18:06
Can you give me some more info about this, @sepidehshahi? Is French added? Is the site being used in French?

**Comment by greatislander** [comment] 2022-08-18 15:23
Resolved by #861. Duplicate of #856.

**Closed as not planned** 2022-08-18 15:23 UTC
Labels: bug, accessibility and usability
