### ISSUE TITLE
Project creation flow: Project team - approximate response time produces 500 error

### ISSUE THREAD

**Issue by cherylhjli** [accessibility-in-action/platform#914] opened 2022-08-23 16:26 UTC
Flow:
- Create project
- Fill in the first page
- Get to the second page, project team
- Fill in everything normally, enter "6" for "approximate response time" (second time I tried this I entered "three days"
- click "save"
- get 500 error
- Go back to dashboard, there is a prompt for creating a new project
<img width="692" alt="Screen Shot 2022-08-23 at 12 15 38 PM" src="https://user-images.githubusercontent.com/9353905/186211222-0c98c67a-12f7-485a-a696-3d5b5e79a0e4.png">
- However on the side of my dashboard under "my active projects" there are a bunch of projects that are marked as drafts, that are probably the ones I have gotten a 500 error on:
<img width="1384" alt="Screen Shot 2022-08-23 at 12 15 51 PM" src="https://user-images.githubusercontent.com/9353905/186211354-8a59b10c-4832-4444-8b62-65ba25aaa9c0.png">
- I click into one of them. the first page loads.
- I click on the second page, "project team" in the side bar
- I get a 500 error again

**Comment by greatislander** [comment] 2022-08-23 16:47
Duplicate of #913.

**Closed as not planned by greatislander** 2022-08-23 16:47 UTC
Labels: bug
