### ISSUE TITLE
SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction (SQL: de...

### ISSUE THREAD

**Issue by marvinroman** [accessibility-in-action/platform#1728] opened 2023-05-31 21:22 UTC
**`Illuminate\Database\QueryException`**

SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction (SQL: delete from `sessions` where `last_activity` <= 1685150713)

:dart: Illuminate\Database\Connection::runQueryCallback
:page_facing_up: /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php

```php
758  // lot more helpful to the developer instead of just the database's errors.
759  catch (Exception $e) {
760*     throw new QueryException(
761          $query, $this->prepareBindings($bindings), $e
762      );
```
[Open in Flare](https://flareapp.io/errors/3839646/latest)

**Comment by marvinroman** [comment] 2023-05-31 21:23
Add slow logging to database to help determine what is causing deadlocks.

```mycnf
[mysqld]
slow_query_log=1
long_query_time=0.1
log_queries_not_using_indexes=1
```

**Comment by jobara** [comment] 2023-06-13 10:46
The related PR (#1782) that closed this was to add additional logging to determine the cause, not a fix for the issue.

**Comment by jobara** [comment] 2024-02-12 15:52
Hasn't re-ocurred for a while.

**Closed as not planned by jobara** 2024-02-12 15:52 UTC
Labels: help wanted, infrastructure
